### ISSUE TITLE
`jaxlib` installed with CUDA build fails to find GPU

### ISSUE THREAD

**Issue by flferretti** [conda-forge/jaxlib-feedstock#285]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

When using `jaxlib` 0.4.32 with CUDA build, `jax` fails to find a GPU:

Environment created with:
```sh
$ conda create -n jaxtest jax jaxlib                                                                conda:jaxtest
```

```console
$ python -c "import jax; jax.print_environment_info()"                                              conda:jaxtest
An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
jax:    0.4.32
jaxlib: 0.4.32
numpy:  2.1.2
python: 3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 16:05:46) [GCC 13.3.0]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='iitbmp014lw015u', release='6.11.0-8-generic', version='#8-Ubuntu SMP PREEMPT_DYNAMIC Mon Sep 16 13:41:20 UTC 2024', machine='x86_64')


$ nvidia-smi
Thu Oct 17 18:57:11 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   54C    P8              4W /   40W |      14MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      3256      G   /usr/bin/gnome-shell                            2MiB |
|    0   N/A  N/A    303067      G   /usr/bin/evolution                              2MiB |
+-----------------------------------------------------------------------------------------+
```

and by checking the versions of the CUDA packages installed, it seems like some packages are missing:

```console
$ python -c "import jax;jax._src.xla_bridge._check_cuda_versions(debug=True)"                       conda:jaxtest
CUDA components status (debug):
Package: CUDA
Version JAX was built against: 12000
Minimum supported: 12010
Installed version: 12060
--------------------------------------------------
Package: cuDNN
Version JAX was built against: 90300
Minimum supported: 9100
Installed version: 90300
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/fferretti-iit.local/miniforge3/envs/jaxtest/lib/python3.12/site-packages/jax/_src/xla_bridge.py", line 421, in _check_cuda_versions
    raise RuntimeError(f'Unable to use CUDA because of the '
RuntimeError: Unable to use CUDA because of the following issues with CUDA components:
Unable to load cuFFT. Is it installed?
Traceback (most recent call last):
  File "/home/fferretti-iit.local/miniforge3/envs/jaxtest/lib/python3.12/site-packages/jax/_src/xla_bridge.py", line 339, in _version_check
    version = get_version()
              ^^^^^^^^^^^^^
RuntimeError: jaxlib/cuda/versions_helpers.cc:54: operation cufftGetVersion(&version) failed: cuFFT internal error

--------------------------------------------------
Unable to load cuSOLVER. Is it installed?
Traceback (most recent call last):
  File "/home/fferretti-iit.local/miniforge3/envs/jaxtest/lib/python3.12/site-packages/jax/_src/xla_bridge.py", line 339, in _version_check
    version = get_version()
              ^^^^^^^^^^^^^
RuntimeError: jaxlib/cuda/versions_helpers.cc:61: operation cusolverGetVersion(&version) failed: cuSolver internal error

--------------------------------------------------
Unable to load cuPTI. Is it installed?
Traceback (most recent call last):
  File "/home/fferretti-iit.local/miniforge3/envs/jaxtest/lib/python3.12/site-packages/jax/_src/xla_bridge.py", line 339, in _version_check
    version = get_version()
              ^^^^^^^^^^^^^
RuntimeError: jaxlib/cuda/versions_helpers.cc:47: operation cuptiGetVersion(&version) failed: Unknown CUPTI error 999. This probably means that JAX was unable to load cupti.

--------------------------------------------------
Unable to load cuBLAS. Is it installed?
Traceback (most recent call last):
  File "/home/fferretti-iit.local/miniforge3/envs/jaxtest/lib/python3.12/site-packages/jax/_src/xla_bridge.py", line 339, in _version_check
    version = get_version()
              ^^^^^^^^^^^^^
RuntimeError: jaxlib/cuda/versions_helpers.cc:71: operation cublasGetVersion( nullptr, &version) failed: cuBlas internal error

--------------------------------------------------
Unable to load cuSPARSE. Is it installed?
Traceback (most recent call last):
  File "/home/fferretti-iit.local/miniforge3/envs/jaxtest/lib/python3.12/site-packages/jax/_src/xla_bridge.py", line 339, in _version_check
    version = get_version()
              ^^^^^^^^^^^^^
RuntimeError: jaxlib/cuda/versions_helpers.cc:80: operation cusparseGetProperty(MAJOR_VERSION, &major) failed: The cuSPARSE library was not found.
```

C.C. @xela-95 @traversaro @diegoferigo

```yaml
### Installed packages

# packages in environment at /home/fferretti-iit.local/miniforge3/envs/jaxtest:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.34.2               heb4867d_0    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
cuda-crt-tools            12.6.77              ha770c72_0    conda-forge
cuda-cudart               12.6.77              h5888daf_0    conda-forge
cuda-cudart_linux-64      12.6.77              h3f2d84a_0    conda-forge
cuda-cupti                12.6.80              hbd13f7d_0    conda-forge
cuda-nvcc-tools           12.6.77              he02047a_0    conda-forge
cuda-nvrtc                12.6.77              hbd13f7d_0    conda-forge
cuda-nvtx                 12.6.77              hbd13f7d_0    conda-forge
cuda-nvvm-tools           12.6.77              he02047a_0    conda-forge
cuda-version              12.6                 h7480c83_3    conda-forge
cudnn                     9.3.0.75             h93bb076_0    conda-forge
importlib-metadata        8.5.0              pyha770c72_0    conda-forge
jax                       0.4.32             pyhd8ed1ab_0    conda-forge
jaxlib                    0.4.32          cuda120py312h9b6c45b_200    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_1    conda-forge
libabseil                 20240722.0      cxx17_h5888daf_1    conda-forge
libblas                   3.9.0           24_linux64_openblas    conda-forge
libcblas                  3.9.0           24_linux64_openblas    conda-forge
libcublas                 12.6.3.3             hbd13f7d_1    conda-forge
libcufft                  11.3.0.4             hbd13f7d_0    conda-forge
libcurand                 10.3.7.77            hbd13f7d_0    conda-forge
libcusolver               11.7.1.2             hbd13f7d_0    conda-forge
libcusparse               12.5.4.2             hbd13f7d_0    conda-forge
libexpat                  2.6.3                h5888daf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgfortran               14.2.0               h69a702a_1    conda-forge
libgfortran-ng            14.2.0               h69a702a_1    conda-forge
libgfortran5              14.2.0               hd5240d6_1    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
libgrpc                   1.65.5               hf5c653b_0    conda-forge
liblapack                 3.9.0           24_linux64_openblas    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libnvjitlink              12.6.77              hbd13f7d_1    conda-forge
libopenblas               0.3.27          pthreads_hac2b453_1    conda-forge
libprotobuf               5.27.5               h5b01275_2    conda-forge
libre2-11                 2024.07.02           hbbce691_1    conda-forge
libsqlite                 3.46.1               hadc24fc_0    conda-forge
libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.2.0               h4852527_1    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
ml_dtypes                 0.5.0           py312hf9745cd_0    conda-forge
nccl                      2.23.4.1             h52f6c39_0    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
numpy                     2.1.2           py312h58c1407_0    conda-forge
openssl                   3.3.2                hb9d3cd8_0    conda-forge
opt-einsum                3.4.0                hd8ed1ab_0    conda-forge
opt_einsum                3.4.0              pyhd8ed1ab_0    conda-forge
pip                       24.2               pyh8b19718_1    conda-forge
python                    3.12.7          hc5c86c4_0_cpython    conda-forge
python_abi                3.12                    5_cp312    conda-forge
re2                       2024.07.02           h77b4e00_1    conda-forge
readline                  8.2                  h8228510_1    conda-forge
scipy                     1.14.1          py312h7d485d2_0    conda-forge
setuptools                75.1.0             pyhd8ed1ab_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.20.2             pyhd8ed1ab_0    conda-forge
```

```yaml
### Environment info


     active environment : None
            shell level : 0
       user config file : /home/fferretti-iit.local/.condarc
 populated config files : /home/fferretti-iit.local/miniforge3/.condarc
                          /home/fferretti-iit.local/.condarc
          conda version : 24.9.1
    conda-build version : not installed
         python version : 3.12.6.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.9.1=0
                          __cuda=12.6=0
                          __glibc=2.40=0
                          __linux=6.11.0=0
                          __unix=0=0
       base environment : /home/fferretti-iit.local/miniforge3  (writable)
      conda av data dir : /home/fferretti-iit.local/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/fferretti-iit.local/miniforge3/pkgs
                          /home/fferretti-iit.local/.conda/pkgs
       envs directories : /home/fferretti-iit.local/miniforge3/envs
                          /home/fferretti-iit.local/.conda/envs
               platform : linux-64
             user-agent : conda/24.9.1 requests/2.32.3 CPython/3.12.6 Linux/6.11.0-8-generic ubuntu/24.10 glibc/2.40 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.9
                UID:GID : 19111:50055
             netrc file : None
           offline mode : False
```
